language:  python
python:
  - "3.6"
services:
  - rabbitmq
  - postgresql
env:
  global:
    - DJANGO_SETTINGS_MODULE="deadline.settings"
    - BUILD_ON_TRAVIS=true

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
  - touch deadline_/deadline/.env && echo 'DB_USER=postgres\nDB_NAME=travis_ci_test\nDB_HOST=localhost\nDB_PASS=\n'
# command to install dependencies
install:
  - "pip install -r deadline_/requirements.txt"
# command to run tests
script:
  - "python deadline_/manage.py makemigrations"
  - "python deadline_/manage.py migrate --run-syncdb" 
  - "python deadline_/manage.py test challenges"
  -  python deadline_/manage.py test accounts

