language:  python
python:
  - "3.6"
services:
  - rabbitmq
env:
  global:
    - DJANGO_SETTINGS_MODULE="deadline.settings"
    - BUILD_ON_TRAVIS=true

# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - "python deadline_/manage.py migrate" 
  - "python deadline_/manage.py test challenges"
  -  python deadline_/manage.py test accounts

